name: FEMM Continuous Integration

on: workflow_dispatch

jobs:
  win-vcpkg:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - uses: lukka/get-cmake@latest

    - name: 'Build FEMM'
      shell: pwsh
      run: ${{ github.workspace }}/build.ps1 -DoNotUpdateTOOL -DisableInteractive -DisableLaTeX -DoNotDeleteBuildFolder

    - name: 'Build Installer'
      run: |
        dir
        7z a windows_msvc.zip .\*

    - uses: actions/upload-artifact@v4.3.0
      with:
        name: FEMM-windows
        path: windows_msvc.zip
        retention-days: 5
